name: Update Content

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: update-content

permissions:
  contents: write

jobs:
  push-changes:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate list and update content
        shell: pwsh
        run: |
          .\scripts\generate-list.ps1

      - name: Commit and push changes
        id: changes
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "chore: automatically update some content [skip ci]"
          git push

  update-docs:
    needs: push-changes
    runs-on: windows-latest
    steps:
      - name: Update Docs
        shell: pwsh
        run: |
          git clone --depth 1 https://${{ secrets.PAT_TOKEN }}@github.com/abgox/schema-docs.git schema-docs
          cd schema-docs
          .\scripts\download-schema-json.ps1
          .\scripts\update-schema-list.ps1

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: automatically update some content"
          git push --force
